Assessment/Areas/Guest/Controllers/OrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assessment.Areas.Guest.Controllers
{
    [Area("Admin")]
    public class OrderController : Controller
    {
        private OrderContext context { get; set; }

        public OrderController(OrderContext ctx)
        {
            context = ctx;
        }

        [HttpGet]
        public IActionResult List()
        {
           

            if (HttpContext.Session.GetString("Guest") == null)
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }
           

            if (HttpContext.Session.GetInt32("OrdersID") != null)
            {
                HttpContext.Session.Remove("OrdersID");
            }

            var Orders = context.orders.Where(d => d.DeleteStatus == "Active").Include(t => t.OrderType).Include(s => s.OrderStatus).OrderBy(o => o.OrdersID);

            return View(Orders);
        }

        public IActionResult Details(int id)
        {
            if (HttpContext.Session.GetString("Guest") == null)
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }

            if (HttpContext.Session.GetInt32("OrdersID") != null)
            {
                HttpContext.Session.Remove("OrdersID");
            }

            HttpContext.Session.SetInt32("OrdersID", id);

            var OrderLine = context.orderLines.Where(o => o.OrdersID == id).Where(s => s.DeleteStatus == "Active").Include(t => t.ProductType).OrderBy(d => d.OrderLineID);

            return View(OrderLine);
        }
    }
}

Assessment/Controllers/SearchController.cs
using Assessment.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace Assessment.Controllers
{
    public class SearchController : Controller
    {
        public readonly IConfiguration _IConfiguration;
        DataAccessLayer data;
        DataTable dt;

        public SearchController(IConfiguration config)
        {
            this._IConfiguration = config;
        }

        [HttpGet]
        public IActionResult SearchOrdersBetweenDates()
        {
            if (HttpContext.Session.GetString("Admin") == null || HttpContext.Session.GetString("Guest")==null)
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }

            return View();
        }

        [HttpPost]
        public IActionResult SearchOrdersBetweenDates(BetweenDatesViewModel dates)
        {
            if (HttpContext.Session.GetString("Admin") == null || HttpContext.Session.GetString("Guest") == null)
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }

            data = new DataAccessLayer(_IConfiguration);
            dt = new DataTable();

            if(ModelState.IsValid)
            {
                dt = data.SearchOrdersBetweenDates(dates.MinDate, dates.MaxDate);

                if(dt.Rows.Count>0)
                {
                    List<Orders> orders = new List<Orders>(); 
                    
                    for(int i=0;i<dt.Rows.Count;i++)
                    {
                        Orders order = new Orders();

                        order.CustomerName = dt.Rows[i]["CustomerName"].ToString();
                        order.OrderNumber = int.Parse(dt.Rows[i]["OrderNumber"].ToString());
                        order.CreatedDate = DateTime.Parse(dt.Rows[i]["CreatedDate"].ToString());

                        orders.Add(order);
                    }

                    var OderList = orders.ToList();

                    return View("ListOrderResults", OderList);

                }
                else
                {
                    ModelState.AddModelError("", "Results not found");
                    return View(dates);
                }
                   

            }
            else
            {
                ModelState.AddModelError("", "Results not found");
                return View(dates);
            }
               

        }

        [HttpGet]
        public IActionResult SearchOrdersByType()
        {
            if (HttpContext.Session.GetString("Admin") == null || HttpContext.Session.GetString("Guest") == null)
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }

            data = new DataAccessLayer(_IConfiguration);
            dt = new DataTable();

            dt = data.GetOrderTypes();

            List<OrderType> orderTypes = new List<OrderType>();

            for(int i = 0; i < dt.Rows.Count; i++)
            {
                OrderType orderType = new OrderType();
                orderType.OrderTypeID = int.Parse(dt.Rows[i]["OrderTypeID"].ToString());
                orderType.TypeDescription = dt.Rows[i]["TypeDescription"].ToString();

                orderTypes.Add(orderType);
            }

            var types = orderTypes.ToList();

            ViewBag.Types = new SelectList(types, "OrderTypeID", "TypeDescription");

            return View();
        }

        [HttpPost]
        public IActionResult SearchOrdersByType(OrderType type)
        {
            if (HttpContext.Session.GetString("Admin") == null || HttpContext.Session.GetString("Guest") == null)
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }

            data = new DataAccessLayer(_IConfiguration);
            dt = new DataTable();
            if(ModelState.IsValid)
            {
                dt = data.SearchOrdersByType(type);

                if (dt.Rows.Count > 0)
                {
                    List<Orders> orders = new List<Orders>();

                    for (int i = 0; i < dt.Rows.Count; i++)
                    {
                        Orders order = new Orders();

                        order.CustomerName = dt.Rows[i]["CustomerName"].ToString();
                        order.OrderNumber = int.Parse(dt.Rows[i]["OrderNumber"].ToString());
                        order.CreatedDate = DateTime.Parse(dt.Rows[i]["CreatedDate"].ToString());

                        orders.Add(order);
                    }

                    var OderList = orders.ToList();

                    return View("ListOrderResults", OderList);

                }
                else
                {
                    dt = data.GetOrderTypes();

                    List<OrderType> orderTypes = new List<OrderType>();

                    for (int i = 0; i < dt.Rows.Count; i++)
                    {
                        OrderType orderType = new OrderType();
                        orderType.OrderTypeID = int.Parse(dt.Rows[i]["OrderTypeID"].ToString());
                        orderType.TypeDescription = dt.Rows[i]["TypeDescription"].ToString();

                        orderTypes.Add(orderType);
                    }

                    var types = orderTypes.ToList();

                    ViewBag.Types = new SelectList(types, "OrderTypeID", "TypeDescription");

                    ModelState.AddModelError("", "Results not found");
                    return View(type);
                }


            }
            else
            {
                dt = data.GetOrderTypes();

                List<OrderType> orderTypes = new List<OrderType>();

                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    OrderType orderType = new OrderType();
                    orderType.OrderTypeID = int.Parse(dt.Rows[i]["OrderTypeID"].ToString());
                    orderType.TypeDescription = dt.Rows[i]["TypeDescription"].ToString();

                    orderTypes.Add(orderType);
                }

                var types = orderTypes.ToList();

                ViewBag.Types = new SelectList(types, "OrderTypeID", "TypeDescription");

                ModelState.AddModelError("", "Results not found");
                return View(type);
            }
        
        }

        [HttpGet]
        public IActionResult SearchOrderLineByProductCode()
        {
            if (HttpContext.Session.GetString("Admin") == null || HttpContext.Session.GetString("Guest") == null)
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }

            return View();
        }

        [HttpPost]
        public IActionResult SearchOrderLineByProductCode(SearchOrderLineVM search)
        {
            if (HttpContext.Session.GetString("Admin") == null || HttpContext.Session.GetString("Guest") == null)
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }

            data = new DataAccessLayer(_IConfiguration);
            dt = new DataTable();

            if(ModelState.IsValid)
            {
                dt = data.SearchOrderLineByProductCode(search);

                if (dt.Rows.Count > 0)
                {
                    List<OrderLine> orderLines = new List<OrderLine>();

                    for (int i = 0; i < dt.Rows.Count; i++)
                    {
                        OrderLine orderLine = new OrderLine();

                        orderLine.LineNumber= int.Parse(dt.Rows[i]["LineNumber"].ToString());
                        orderLine.ProductCode= dt.Rows[i]["ProductCode"].ToString();
                        orderLine.ProductCostPrice = double.Parse(dt.Rows[i]["ProductCostPrice"].ToString());
                        orderLine.ProductSalePrice= double.Parse(dt.Rows[i]["ProductSalePrice"].ToString());
                        orderLine.Quantity= int.Parse(dt.Rows[i]["Quantity"].ToString());
                        orderLine.OrdersID= int.Parse(dt.Rows[i]["OrdersID"].ToString());

                        orderLines.Add(orderLine);
                    }

                    var OrderLineList = orderLines.ToList();

                    return View("OrderLinesResults", OrderLineList);

                }
                else
                {
                    ModelState.AddModelError("", "Results not found");
                    return View(search);
                }

            }
            else
            {
                ModelState.AddModelError("", "Results not found");
                return View(search);
            }
        }
    }
}

Assessment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assessment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Assessment</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="List">List Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="SearchOrdersBetweenDates">Search orders by dates</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="SearchOrdersByType">Search orders by Type</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="SearchOrderLineByProductCode">Search orderline</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-nav navbar-right">
                    <a asp-action="Logout" asp-area="" asp-controller="Home" class="btn btn-primary bg-danger">Logout</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Assessment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>