Assessment/Models/OrderLine.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Assessment.Models
{
    public class OrderLine
    {
        public int OrderLineID { get; set; }
 
        public int LineNumber { get; set; }
        [Required(ErrorMessage ="Please enter product code")]
        public string ProductCode { get; set; }
        [Required(ErrorMessage ="Please enter product cost price.")]
        public double ProductCostPrice { get; set; }
        [Required(ErrorMessage ="[lease enter Product Sales product.")]
        public double ProductSalePrice { get; set; }
        [Required(ErrorMessage ="Please enter quantity.")]
        public int Quantity { get; set; }

        [Required(ErrorMessage ="Select Product type")]
        public int ProductTypeID { get; set; }
        public ProductType ProductType { get; set; }

        [Required(ErrorMessage ="Please select order.")]
        public int OrdersID { get; set; }
        public Orders Orders { get; set; }

        public string DeleteStatus { get; set; }
    }
}

Assessment/Controllers/OrderLineController.cs
using Assessment.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace Assessment.Controllers
{
    public class OrderLineController : Controller
    {
        public readonly IConfiguration _IConfiguration;
        DataAccessLayer data;
        DataTable dt;

        public OrderLineController(IConfiguration config)
        {
            this._IConfiguration = config;
        }

        [HttpGet]
        public IActionResult Add()
        {
            if (HttpContext.Session.GetString("Admin") == null)
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }

            data = new DataAccessLayer(_IConfiguration);
            dt = new DataTable();

            dt=data.GetProductType();

            List<ProductType> productTypes = new List<ProductType>();
            
            for(int i=0;i<dt.Rows.Count;i++)
            {
                ProductType productType = new ProductType();

                productType.ProductTypeID = int.Parse(dt.Rows[i]["ProductTypeID"].ToString());
                productType.ProductTypeDescription = dt.Rows[i]["ProductTypeDescription"].ToString();

                productTypes.Add(productType);
            }

            var getTypes = productTypes.ToList();

            ViewBag.Types = new SelectList(getTypes, "ProductTypeID", "ProductTypeDescription");

            return View();
        }

        [HttpPost]
        public IActionResult Add(OrderLine line)
        {
            if (HttpContext.Session.GetString("Admin") == null)
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }

            data = new DataAccessLayer(_IConfiguration);
            if (ModelState.IsValid)
            {

                #region Line number increament
                int ordersID = (int)HttpContext.Session.GetInt32("OrdersID");

                dt = new DataTable();

                dt = data.GetLineNumberCount(ordersID);
                int counter;

                try
                {
                    counter = int.Parse(dt.Rows[0]["CounterCol"].ToString());
                }
                catch
                {
                    counter = 0;
                }

                counter++;
                

                #endregion

                line.LineNumber = counter;

                data.AddOrderLine(line);

                return RedirectToAction("List", "Order");
            }
            else
            {
                dt = new DataTable();

                dt = data.GetProductType();

                List<ProductType> productTypes = new List<ProductType>();

                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    ProductType productType = new ProductType();

                    productType.ProductTypeID = int.Parse(dt.Rows[i]["ProductTypeID"].ToString());
                    productType.ProductTypeDescription = dt.Rows[i]["ProductTypeDescription"].ToString();

                    productTypes.Add(productType);
                }

                var getTypes = productTypes.ToList();

                ViewBag.Types = new SelectList(getTypes, "ProductTypeID", "ProductTypeDescription");

                return View(line);
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (HttpContext.Session.GetString("Admin") == null)
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }

            data = new DataAccessLayer(_IConfiguration);

            dt = new DataTable();

            dt = data.GetOrderLineByID(id);

            OrderLine line = new OrderLine();
            if (dt.Rows.Count>0)
            {
                
                line.ProductCode = dt.Rows[0]["ProductCode"].ToString();
                line.LineNumber = int.Parse(dt.Rows[0]["LineNumber"].ToString());
                line.ProductTypeID = int.Parse(dt.Rows[0]["ProductTypeID"].ToString());
                line.ProductCostPrice = double.Parse(dt.Rows[0]["ProductCostPrice"].ToString());
                line.ProductSalePrice = double.Parse(dt.Rows[0]["ProductSalePrice"].ToString());
                line.Quantity = int.Parse(dt.Rows[0]["Quantity"].ToString());
                line.OrdersID= int.Parse(dt.Rows[0]["OrdersID"].ToString());
                line.OrderLineID= int.Parse(dt.Rows[0]["OrderLineID"].ToString());
            }

            DataTable dtType = new DataTable();
            dtType = data.GetProductType();

            List<ProductType> productTypes = new List<ProductType>();

            for (int i = 0; i < dtType.Rows.Count; i++)
            {
                ProductType productType = new ProductType();

                productType.ProductTypeID = int.Parse(dtType.Rows[i]["ProductTypeID"].ToString());
                productType.ProductTypeDescription = dtType.Rows[i]["ProductTypeDescription"].ToString();

                productTypes.Add(productType);
            }

            var getTypes = productTypes.ToList();

            ViewBag.Types = new SelectList(getTypes, "ProductTypeID", "ProductTypeDescription");

            return View(line);
        }

        [HttpPost]
        public IActionResult Edit(OrderLine line)
        {
            if (HttpContext.Session.GetString("Admin") == null)
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }

            data = new DataAccessLayer(_IConfiguration);

            if(ModelState.IsValid)
            {
                data.UpdateOrderLine(line);
                int id = (int)HttpContext.Session.GetInt32("OrdersID");
                return RedirectToAction("Details", "Order", new { id=id});
            }
            else
            {
                dt = new DataTable();
                dt = data.GetProductType();

                List<ProductType> productTypes = new List<ProductType>();

                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    ProductType productType = new ProductType();

                    productType.ProductTypeID = int.Parse(dt.Rows[i]["ProductTypeID"].ToString());
                    productType.ProductTypeDescription = dt.Rows[i]["ProductTypeDescription"].ToString();

                    productTypes.Add(productType);
                }

                var getTypes = productTypes.ToList();

                ViewBag.Types = new SelectList(getTypes, "ProductTypeID", "ProductTypeDescription");

                return View(line);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (HttpContext.Session.GetString("Admin") == null)
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }

            data = new DataAccessLayer(_IConfiguration);
            dt = new DataTable();

            dt = data.GetOrderLineByID(id);

            OrderLine line = new OrderLine();
            if (dt.Rows.Count > 0)
            {

                line.ProductCode = dt.Rows[0]["ProductCode"].ToString();
                line.LineNumber = int.Parse(dt.Rows[0]["LineNumber"].ToString());
                line.ProductTypeID = int.Parse(dt.Rows[0]["ProductTypeID"].ToString());
                line.ProductCostPrice = double.Parse(dt.Rows[0]["ProductCostPrice"].ToString());
                line.ProductSalePrice = double.Parse(dt.Rows[0]["ProductSalePrice"].ToString());
                line.Quantity = int.Parse(dt.Rows[0]["Quantity"].ToString());
                line.OrdersID = int.Parse(dt.Rows[0]["OrdersID"].ToString());
                line.OrderLineID = int.Parse(dt.Rows[0]["OrderLineID"].ToString());
            }

            return View(line);
        }

        [HttpPost]
        public IActionResult Delete(OrderLine line)
        {
            if (HttpContext.Session.GetString("Admin") == null)
            {
                return RedirectToAction("Login", "Home", new { area = "" });
            }

            data = new DataAccessLayer(_IConfiguration);

            data.DeleteOrderLine(line);

            int id = (int)HttpContext.Session.GetInt32("OrdersID");

            return RedirectToAction("Details", "Order", new { id = id });
        }
    }
}

Assessment/Views/OrderLine/Add.cshtml
@model Assessment.Models.OrderLine
@using Microsoft.AspNetCore.Http;
@{
    ViewData["Title"] = "Add";

    
}

<h1>Add</h1>

<h4>OrderLine</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="ProductCode" class="control-label"></label>
                <input asp-for="ProductCode" class="form-control" />
                <span asp-validation-for="ProductCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductCostPrice" class="control-label"></label>
                <input asp-for="ProductCostPrice" class="form-control" />
                <span asp-validation-for="ProductCostPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductSalePrice" class="control-label"></label>
                <input asp-for="ProductSalePrice" class="form-control" />
                <span asp-validation-for="ProductSalePrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductTypeID" class="control-label"></label>
                <select asp-for="ProductTypeID" class="form-control" asp-items="ViewBag.Types"></select>
            </div>

            <input type="hidden" asp-for="OrdersID" value="@Context.Session.GetInt32("OrdersID")" class="form-control" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Order" asp-action="Details" asp-route-id="@Context.Session.GetInt32("OrdersID")">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Assessment/Views/OrderLine/Delete.cshtml
@model Assessment.Models.OrderLine
@using Microsoft.AspNetCore.Http;
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OrderLine</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LineNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LineNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProductCode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProductCode)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProductCostPrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProductCostPrice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProductSalePrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProductSalePrice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>



    </dl>

    <form asp-controller="OrderLine" asp-action="Delete" method="post">
        <input type="hidden" asp-for="OrdersID" />
        <input type="hidden" asp-for="ProductCode" />
        <input type="hidden" asp-for="ProductCostPrice" />
        <input type="hidden" asp-for="ProductSalePrice" />
        <input type="hidden" asp-for="OrderLineID" />
        <input type="hidden" asp-for="ProductTypeID" />
        <input type="hidden" asp-for="Quantity" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="Order" asp-action="Details" asp-route-id="@Context.Session.GetInt32("OrdersID")">Back to List</a>
    </form>
</div>

Assessment/Views/OrderLine/Edit.cshtml
@model Assessment.Models.OrderLine

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>OrderLine</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="OrderLine" asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderLineID" />
            <div class="form-group">
                <label asp-for="LineNumber" class="control-label"></label>
                <input asp-for="LineNumber" class="form-control" disabled />
                <input asp-for="LineNumber" class="form-control" type="hidden" />
                <span asp-validation-for="LineNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductCode" class="control-label"></label>
                <input asp-for="ProductCode" class="form-control" />
                <span asp-validation-for="ProductCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductCostPrice" class="control-label"></label>
                <input asp-for="ProductCostPrice" class="form-control" />
                <span asp-validation-for="ProductCostPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductSalePrice" class="control-label"></label>
                <input asp-for="ProductSalePrice" class="form-control" />
                <span asp-validation-for="ProductSalePrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductTypeID" class="control-label"></label>
                <select asp-for="ProductTypeID" class="form-control" asp-items="ViewBag.Types">
                    <option value="@Model.ProductTypeID" selected></option>
                </select>
                <span asp-validation-for="ProductTypeID" class="text-danger"></span>
            </div>
            <input asp-for="OrdersID" type="hidden" class="form-control" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}